# Stage 1: Build
FROM node:22-alpine AS builder
WORKDIR /app

# package.json 및 package-lock.json 먼저 복사하고 종속성 설치
COPY package*.json ./
RUN npm install --legacy-peer-deps

# 소스 파일을 복사하고 빌드
COPY . .

ARG GENERATE_SOURCEMAP
ARG REACT_APP_GRAPHQL_URI
ARG REACT_APP_YOUTUBE_API_KEY
ARG REACT_APP_YOUTUBE_CHANNEL_ID
ARG REACT_APP_YOUTUBE_SUNDAYPLAYLIST_ID
ARG REACT_APP_YOUTUBE_FRIDAYPLAYLIST_ID
ARG REACT_APP_YOUTUBE_SPECIAL_PRAISE_ID
ARG REACT_APP_YOUTUBE_WEDNESDAY_PRAISE_ID
ARG REACT_APP_YOUTUBE_SUNDAY_PRAISE_ID
ARG REACT_APP_YOUTUBE_YOUTH_WORSHIP_ID
ARG REACT_APP_KAKAO_MAP_KEY

ENV GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP
ENV REACT_APP_GRAPHQL_URI=$REACT_APP_GRAPHQL_URI
ENV REACT_APP_YOUTUBE_API_KEY=$REACT_APP_YOUTUBE_API_KEY
ENV REACT_APP_YOUTUBE_CHANNEL_ID=$REACT_APP_YOUTUBE_CHANNEL_ID
ENV REACT_APP_YOUTUBE_SUNDAYPLAYLIST_ID=$REACT_APP_YOUTUBE_SUNDAYPLAYLIST_ID
ENV REACT_APP_YOUTUBE_FRIDAYPLAYLIST_ID=$REACT_APP_YOUTUBE_FRIDAYPLAYLIST_ID
ENV REACT_APP_YOUTUBE_SPECIAL_PRAISE_ID=$REACT_APP_YOUTUBE_SPECIAL_PRAISE_ID
ENV REACT_APP_YOUTUBE_WEDNESDAY_PRAISE_ID=$REACT_APP_YOUTUBE_WEDNESDAY_PRAISE_ID
ENV REACT_APP_YOUTUBE_SUNDAY_PRAISE_ID=$REACT_APP_YOUTUBE_SUNDAY_PRAISE_ID
ENV REACT_APP_YOUTUBE_YOUTH_WORSHIP_ID=$REACT_APP_YOUTUBE_YOUTH_WORSHIP_ID
ENV REACT_APP_KAKAO_MAP_KEY=$REACT_APP_KAKAO_MAP_KEY

RUN npm run build

# Stage 2: Production
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# 🌟 [수정] /app/dist를 /app/build로 변경하여 빌드 결과물을 올바르게 가져옵니다.
COPY --from=builder /app/build .

# Nginx 설정 파일 복사
COPY ./conf/default.conf /etc/nginx/conf.d/default.conf 

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]