FROM node:18 as build
WORKDIR /app
COPY package.json .
COPY . .
RUN npm install
RUN npm run build


FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf 
// 같은 디렉토리에 있는 nginx.conf 파일 복사 

COPY --from=build /app/build /usr/share/nginx/html  
//임시로 만든 build 이미지를 가져와서 그 파일을 nginx/html에 복붙!

EXPOSE 80  //port 개방 

CMD ["nginx", "-g", "daemon off;"]